import type { Product } from "@/types";

export const products: Product[] = [
  {
    id: "revox-serum",
    name: "Niacinamide Serum",
    brand: "Luxe Beauty",
    categoryId: "skincare",
    storeId: "glow-market",
    price: 120,
    originalPrice: 159,
    currency: "SAR",
    rating: 4.8,
    reviewCount: 95,
    storeCount: 7,
    discountPercent: 40,
    image: "/images/products/revox-serum.png",
    isFeatured: true,
  },
  {
    id: "versace-eros",
    name: "Oriental Eau Perfume",
    brand: "Glow Center",
    categoryId: "fragrance",
    storeId: "beauty-house",
    price: 340,
    originalPrice: 417.5,
    currency: "SAR",
    rating: 4.9,
    reviewCount: 75,
    storeCount: 23,
    discountPercent: 40,
    image: "/images/products/versace-eros.png",
  },
  {
    id: "lip-serum",
    name: "Protecting Nail Paint",
    brand: "Luxe Beauty",
    categoryId: "skincare",
    storeId: "rose-cart",
    price: 70,
    originalPrice: 148,
    currency: "SAR",
    rating: 4.7,
    reviewCount: 78,
    storeCount: 7,
    discountPercent: 40,
    image: "/images/products/lip-serum.png",
  },
  {
    id: "versace-eros-large",
    name: "AHA BHA Serum",
    brand: "Luxe Beauty",
    categoryId: "fragrance",
    storeId: "glow-market",
    price: 120,
    originalPrice: 499,
    currency: "SAR",
    rating: 4.8,
    reviewCount: 89,
    storeCount: 7,
    discountPercent: 40,
    image: "/images/products/versace-eros-large.png",
  },
  {
    id: "concealer-palette",
    name: "Concealer Pallette",
    brand: "Luxe Beauty",
    categoryId: "makeup",
    storeId: "glow-market",
    price: 120,
    originalPrice: 159,
    currency: "SAR",
    rating: 4.8,
    reviewCount: 95,
    storeCount: 7,
    discountPercent: 40,
    image: "/images/products/peach-glow-palette.svg",
  },
  {
    id: "correcting-powder",
    name: "Rare Correcting Powder",
    brand: "Glow Center",
    categoryId: "makeup",
    storeId: "beauty-house",
    price: 140,
    originalPrice: 200,
    currency: "SAR",
    rating: 4.5,
    reviewCount: 75,
    storeCount: 23,
    discountPercent: 40,
    image: "/images/categories/makeup.png",
  },
  {
    id: "smooth-foundation",
    name: "Silk Smooth Foundation",
    brand: "Luxe Beauty",
    categoryId: "makeup",
    storeId: "rose-cart",
    price: 310,
    originalPrice: 420,
    currency: "SAR",
    rating: 4.7,
    reviewCount: 78,
    storeCount: 7,
    discountPercent: 40,
    image: "/images/products/rose-serum.svg",
  },
  {
    id: "nude-eye-shadow",
    name: "Nude Eye Shadow Pallette",
    brand: "Luxe Beauty",
    categoryId: "makeup",
    storeId: "glow-market",
    price: 220,
    originalPrice: 310,
    currency: "SAR",
    rating: 4.8,
    reviewCount: 89,
    storeCount: 7,
    discountPercent: 40,
    image: "/images/products/peach-glow-palette.svg",
  },
];
