import type { Store } from "@/types";

export const stores: Store[] = [
  {
    id: "luxe-beauty",
    name: "Luxe Beauty",
    logo: "/images/stores/luxe-beauty.png",
    image: "/images/stores/luxe-beauty.png",
    rating: 4.8,
    reviewCount: 95,
    storeCount: 20,
    productCount: 900,
    workingHours: "8:00 AM - 11:00 PM",
    deliveryLabel: "Same day delivery",
  },
  {
    id: "glam-bar",
    name: "Glam Bar",
    logo: "/images/stores/glam-bar.png",
    image: "/images/stores/glam-bar.png",
    rating: 4.6,
    reviewCount: 89,
    storeCount: 16,
    productCount: 1200,
    workingHours: "8:00 AM - 11:00 PM",
    deliveryLabel: "Free delivery over AED 150",
  },
  {
    id: "shoppee-hub",
    name: "Shoppee Hub",
    logo: "/images/stores/shoppee-hub.png",
    image: "/images/stores/shoppee-hub.png",
    rating: 4.7,
    reviewCount: 89,
    storeCount: 16,
    productCount: 1200,
    workingHours: "8:00 AM - 11:00 PM",
    deliveryLabel: "Fast local shipping",
  },
  {
    id: "ela-de-pure",
    name: "Ela De Pure",
    logo: "/images/stores/ela-de-pure.png",
    image: "/images/stores/ela-de-pure.png",
    rating: 4.5,
    reviewCount: 94,
    storeCount: 4,
    productCount: 200,
    workingHours: "8:00 AM - 11:00 PM",
    deliveryLabel: "Premium skincare picks",
  },
  {
    id: "sephora",
    name: "Sephora",
    logo: "/images/stores/sephora-store.png",
    image: "/images/stores/sephora-store.png",
    rating: 4.9,
    reviewCount: 200,
    storeCount: 70,
    productCount: 5000,
    workingHours: "8:00 AM - 11:00 PM",
    deliveryLabel: "Luxury beauty brands",
  },
  {
    id: "fair-glow",
    name: "Fair Glow",
    logo: "/images/stores/fair-glow.png",
    image: "/images/stores/fair-glow.png",
    rating: 4.4,
    reviewCount: 200,
    storeCount: 70,
    productCount: 5000,
    workingHours: "8:00 AM - 11:00 PM",
    deliveryLabel: "Glow essentials nearby",
  },
];
